name: restaurant_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0



dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  sqlite3: ^2.4.2
